version: '3.1'

services:
  app:
    build: .
    env_file:
      - .test.env
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    env_file:
      - .test.env
    ports:
      - '5432:5432'